### PR TITLE
Additional unit tests and bug fixes

### PR DESCRIPTION
**Pull request by simetenn**
Fixed a wide variety of bugs, implemented all relevant unit tests from h5py and implemented a few h5py features. Contains some API changes and must be reviewed/changed.

Major changes that potentially could break something:

- `create_dataset`, `require_dataset` and set_data now has support for creating data with shape, dtype, data and fillvalue. Should these be able to overwrite data if it already exists? Should set_data keep the data in memory or write it to file, and then load the data back from file when necessary?
        
        Group.create_dataset(name, shape=None, dtype=None, data=None, fillvalue=None):
        Group.require_dataset(name, shape=None, dtype=None, data=None, fillvalue=None):
        Dataset.set_data(shape=None, dtype=None, data=None, fillvalue=None):

- Group.require_dataset requires exact same shape and dtype (as h5py does). Currently it overwrites the dataset if given data. Change this to raise an error?
- Dataset `__getitem__` returns quantities if the saved data was a quantity.
- `"/name"` can only be used from root directory in all classes
- `create_raw` and `require_raw`returns a `Raw` object instead of the dictionary name
- Implemented Raw `__eq__()`
- Fixed bug where `os.sep` was used instead of `"/"`
- Group.create_group tests for read only mode
- names can end with an arbitrary number of `"/"`, `name/////`
- Group `keys`, `items` and `values` return view objects
- Test for valid filenames when creating an exdir file
- Dataset has support for size, `__iter__`, dtype, `__eq__` and `__len__`.
- IOError when giving wrong read mode and naming rule changed to TypeError

### CODE REVIEW

**Comment by dragly** [comment]
Looks good and I think this can be merged as is. But before we do that, could you add a copyright statement to any relevant files where tests are copied from h5py? Something along the lines of

```python
# This file is part of Exdir, the Experimental Directory Structure.
# 
# Copyright 2017 Simen Tennøe
#
# License: MIT, see "LICENSE" file for the full license terms.
#
# This file contains code from h5py, a Python interface to the HDF5 library,
# licensed under a standard 3-clause BSD license 
# with copyright Andrew Collette and contributors.
# See http://www.h5py.org and the "3rdparty/h5py-LICENSE" file for details.
```

And add the following to "3rdparty/h5py-LICENSE":

```
Copyright Notice and Statement for the h5py Project
===================================================

    Copyright (c) 2008-2013 Andrew Collette and contributors
    http://www.h5py.org
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are
    met:

    a. Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    b. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the
       distribution.

    c. Neither the name of the author nor the names of contributors may 
       be used to endorse or promote products derived from this software 
       without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
    A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
    OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
    SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
    LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
    DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
    THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
    OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by simetenn** [comment]
Copyright statements have been added and the pr can be merged. But be aware that this pr can break existing code with the changes to create_dataset.

**Comment by lepmik** [comment]
great work!

Before we merge, can you fix the failing doctest on require_dataset?

**Comment by simetenn** [comment]
Was not the failing doctests fixed in commit 12814c503491987eb70298f13684643a44882c3b? Or are there more failing doctests?

**Comment by lepmik** [comment]
oh, yes, somehow the travis report I was looking at was not updated. It all looks good now. Ok to merge for me, the breakage will not affect CINPLA users before exdir is pulled via subrepo in `expipe-dev` .

**Pull request merged**
